baseURL: "https://drkassai.com/" 
title: Kasra Kassai
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        

params:
    description: "I’m a Lecturer in Digital Analytics at London South Bank University, where I combine teaching and research to drive advancements in machine learning, edge computing, and sustainable computing practices. My work focuses on creating practical solutions for energy-efficient systems and carbon-aware applications. I hold a BSc (Hons) in Computer Science and an MSc in Software Engineering from City, University of London. At LSBU, I completed a PhD in Computer Science under Professor Tasos Dagiuklas, contributing to frameworks for sustainable computing in 6G."
    author: Dr. Kasra Kassai
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Dr. Kasra Kassai
          subtitle: "I’m a Lecturer in Digital Analytics at London South Bank University, where I combine teaching and research to drive advancements in machine learning, edge computing, and sustainable computing practices. My work focuses on creating practical solutions for energy-efficient systems and carbon-aware applications. I hold a BSc (Hons) in Computer Science and an MSc in Software Engineering from City, University of London. At LSBU, I completed a PhD in Computer Science under Professor Tasos Dagiuklas, contributing to frameworks for sustainable computing in 6G."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            

    socialIcons:
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Website
          url: https://researchportal.lsbu.ac.uk/en/persons/kasra-kassai
        - name: LinkedIn
          url: https://www.linkedin.com/in/kasrakassai/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=zABNP3sAAAAJ&hl=en  
        - name: Email
          url: mailto:kasra.kassai@lsbu.ac.uk
        - name: Phone
          url: https://outlook.office.com/bookwithme/user/c394f8da16644397b41d867b3f251d31@lsbu.ac.uk?anonymous&ep=plink
        - name: GitHub
          url: https://github.com/seekasra
        - name: X
          url: https://twitter.com/kasrakassai

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Moritz-Maria von Igelfeld"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2